In [27]:
import numpy as np
import pandas as pd

In [42]:
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import  cross_val_score

In [29]:
df = pd.read_csv('titanic_train.csv' , usecols =['Age' , 'Fare', 'Parch', 'Survived', 'SibSp'])

In [30]:
df.dropna(inplace = True)

In [31]:
df.head()

   Survived   Age  SibSp  Parch     Fare
0         0  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         1  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         0  35.0      0      0   8.0500

In [32]:
df['Family'] = df['SibSp'] + df['Parch']

In [33]:
df.head()

   Survived   Age  SibSp  Parch     Fare  Family
0         0  22.0      1      0   7.2500       1
1         1  38.0      1      0  71.2833       1
2         1  26.0      0      0   7.9250       0
3         1  35.0      1      0  53.1000       1
4         0  35.0      0      0   8.0500       0

In [34]:
df.drop(columns = ['Parch', 'SibSp'] , inplace = True)

In [35]:
df.sample(10)

     Survived   Age      Fare  Family
405         0  34.0   21.0000       1
435         1  14.0  120.0000       3
58          1   5.0   27.7500       3
70          0  32.0   10.5000       0
498         0  25.0  151.5500       3
512         1  36.0   26.2875       0
820         1  52.0   93.5000       2
206         0  32.0   15.8500       1
106         1  21.0    7.6500       0
353         0  25.0   17.8000       1

In [36]:
x = df.drop(columns = ['Survived'])
y = df['Survived']

In [38]:
x_train , x_test , y_train, y_test = train_test_split(df.drop(columns = ['Survived']), df['Survived'] ,test_size = 0.2, random_state = 42)

In [39]:
x_train.head()

      Age     Fare  Family
328  31.0  20.5250       2
73   26.0  14.4542       1
253  30.0  16.1000       1
719  33.0   7.7750       0
666  25.0  13.0000       0

In [40]:
#without binarization
clf = DecisionTreeClassifier()

clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)

accuracy_score(y_test, y_pred)

0.6223776223776224

In [43]:
np.mean(cross_val_score(DecisionTreeClassifier(), x, y , cv = 10 , scoring = 'accuracy'))

np.float64(0.6541275430359936)

In [44]:
#applying binarization

from sklearn.preprocessing import Binarizer

In [45]:
trf = ColumnTransformer([
    ('bin' , Binarizer(copy = False),['Family'])
], remainder= 'passthrough')

In [46]:
x_train_trf = trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)

In [48]:
pd.DataFrame(x_train_trf , columns = ['Family' ,'Age' , 'Fare'])

     Family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [52]:
clf = DecisionTreeClassifier()
clf.fit(x_train_trf, y_train)
y_pred2 = clf.predict(x_test_trf)

accuracy_score(y_test , y_pred2)

0.6293706293706294

In [53]:
x_trf = trf.fit_transform(x)
np.mean(cross_val_score(DecisionTreeClassifier(), x, y , cv = 10 , scoring = 'accuracy'))

np.float64(0.6513302034428795)