In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import SimpleImputer,MissingIndicator

In [3]:
df = pd.read_csv('titanic_train.csv' , usecols = ['Age' , 'Fare' , 'Survived'])

In [4]:
df.sample(10)

     Survived   Age      Fare
824         0   2.0   39.6875
453         1  49.0   89.1042
352         0  15.0    7.2292
356         1  22.0   55.0000
799         0  30.0   24.1500
544         0  50.0  106.4250
503         0  37.0    9.5875
531         0   NaN    7.2292
43          1   3.0   41.5792
506         1  33.0   26.0000

In [5]:
x = df.drop(columns = ['Survived'])
y = df['Survived']

In [6]:
x_train , x_test , y_train , y_test = train_test_split(x, y , test_size = 0.2, random_state = 2)

In [7]:
x_train.head()

      Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

In [21]:
si = SimpleImputer()
#missing values got replaced by mean values using simple imputer
x_train_trf = si.fit_transform(x_train)
x_test_trf = si.transform(x_test)

In [60]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf , y_train)
y_pred = clf.predict(x_test_trf)

In [13]:
x_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]], shape=(712, 2))

In [14]:
y_train

30     0
10     1
873    0
182    0
876    0
      ..
534    0
584    0
493    0
527    0
168    0
Name: Survived, Length: 712, dtype: int64

In [19]:
y_pred.shape

(179,)

In [17]:
y_test.shape

(179,)

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.6145251396648045

In [ ]:
#with missing indicator

In [ ]:
from sklearn.linear_model import LogisticRegression

In [22]:
mi = MissingIndicator()
clf = LogisticRegression()

x_train_trf2 = mi.fit_transform(x_train)
x_test_trf2 = mi.transform(x_test)

In [30]:
x_train_trf2

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True]])

In [32]:
x_train['Age_na'] = x_train_trf2
x_train.sample(10)

       Age      Fare  Age_na
545  64.00   26.0000   False
796  49.00   25.9292   False
806  39.00    0.0000   False
277    NaN    0.0000    True
598    NaN    7.2250    True
224  38.00   90.0000   False
14   14.00    7.8542   False
802  11.00  120.0000   False
755   0.67   14.5000   False
778    NaN    7.7375    True

In [ ]:
#the above data form is what missing inidcator does . rest of the process is same

In [33]:
x_test_trf2

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False]])

In [55]:
x_test['Age_na'] = x_test_trf2

In [65]:
x_test_trf2

array([[ 42.        ,  26.2875    ,   0.        ],
       [ 21.        ,   8.05      ,   0.        ],
       [ 24.        ,  65.        ,   0.        ],
       [ 28.        ,  56.4958    ,   0.        ],
       [ 17.        ,   7.925     ,   0.        ],
       [ 30.        ,   7.8958    ,   0.        ],
       [ 80.        ,  30.        ,   0.        ],
       [ 25.        ,   7.25      ,   0.        ],
       [ 50.        , 133.65      ,   0.        ],
       [ 25.        ,  26.        ,   0.        ],
       [ 35.        ,  26.        ,   0.        ],
       [ 35.        ,  90.        ,   0.        ],
       [ 55.        ,  16.        ,   0.        ],
       [ 29.78590426,  56.4958    ,   1.        ],
       [ 29.78590426,  56.4958    ,   1.        ],
       [ 19.        ,   7.8542    ,   0.        ],
       [ 29.78590426,  15.2458    ,   1.        ],
       [ 49.        ,   0.        ,   0.        ],
       [ 18.        ,  14.4542    ,   0.        ],
       [ 65.        ,   7.75      ,   0.        ],
       [ 18.        , 108.9       ,   0.        ],
       [ 29.78590426,  22.3583    ,   1.        ],
       [ 16.        ,  18.        ,   0.        ],
       [ 21.        ,   9.825     ,   0.        ],
       [ 19.        ,   6.75      ,   0.        ],
       [  1.        ,  11.1333    ,   0.        ],
       [ 50.        ,  10.5       ,   0.        ],
       [ 37.        ,  53.1       ,   0.        ],
       [ 28.        ,   9.5       ,   0.        ],
       [ 54.        ,  14.        ,   0.        ],
       [ 20.        ,   7.925     ,   0.        ],
       [ 36.        ,   0.        ,   0.        ],
       [  6.        ,  31.275     ,   0.        ],
       [ 29.78590426,  50.        ,   1.        ],
       [ 40.        ,  31.        ,   0.        ],
       [ 26.        ,  16.1       ,   0.        ],
       [ 30.        ,  93.5       ,   0.        ],
       [  1.        ,  46.9       ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 35.        ,  10.5       ,   0.        ],
       [ 38.        ,   7.05      ,   0.        ],
       [ 44.        ,  16.1       ,   0.        ],
       [ 22.        ,   7.75      ,   0.        ],
       [ 18.        ,   6.4958    ,   0.        ],
       [ 21.        ,   8.4333    ,   0.        ],
       [ 29.78590426, 227.525     ,   1.        ],
       [ 21.        ,  77.9583    ,   0.        ],
       [ 29.78590426,   8.6625    ,   1.        ],
       [ 22.        ,   7.225     ,   0.        ],
       [ 27.        ,  10.5       ,   0.        ],
       [ 29.78590426,   8.05      ,   1.        ],
       [ 51.        ,  26.55      ,   0.        ],
       [ 28.        ,  33.        ,   0.        ],
       [ 47.        ,  38.5       ,   0.        ],
       [ 32.        ,  10.5       ,   0.        ],
       [ 48.        ,  52.        ,   0.        ],
       [ 10.        ,  24.15      ,   0.        ],
       [ 21.        ,   8.6625    ,   0.        ],
       [ 51.        ,   7.0542    ,   0.        ],
       [ 32.        ,   7.925     ,   0.        ],
       [ 42.        ,  13.        ,   0.        ],
       [  2.        ,  26.        ,   0.        ],
       [ 35.        ,   8.05      ,   0.        ],
       [ 29.78590426,   7.25      ,   1.        ],
       [  2.        ,  10.4625    ,   0.        ],
       [ 33.        ,   9.5       ,   0.        ],
       [ 48.        ,  25.9292    ,   0.        ],
       [ 55.        ,  30.5       ,   0.        ],
       [  1.        ,  39.6875    ,   0.        ],
       [ 17.        ,   7.0542    ,   0.        ],
       [ 24.        ,  15.85      ,   0.        ],
       [ 74.        ,   7.775     ,   0.        ],
       [ 29.78590426,  24.15      ,   1.        ],
       [ 28.        ,   7.7958    ,   0.        ],
       [ 26.        ,   7.8542    ,   0.        ],
       [  1.        ,  39.        ,   0.        ],
       [ 18.        ,   8.05      ,   0.        ],
       [  3.        ,  26.        ,   0.        ],
       [ 48.        ,  39.6       ,   0.        ],
       [ 32.        ,  56.4958    ,   0.        ],
       [ 19.        ,  91.0792    ,   0.        ],
       [ 29.78590426,  42.4       ,   1.        ],
       [ 70.        ,  10.5       ,   0.        ],
       [ 34.        ,  26.        ,   0.        ],
       [ 39.        , 110.8833    ,   0.        ],
       [ 17.        ,  10.5       ,   0.        ],
       [ 38.        ,   8.6625    ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 30.        ,  21.        ,   0.        ],
       [ 28.        ,  13.        ,   0.        ],
       [ 29.78590426,   7.725     ,   1.        ],
       [ 19.        ,   8.1583    ,   0.        ],
       [ 29.        ,   7.75      ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 44.        ,   7.925     ,   0.        ],
       [ 22.        ,  41.5792    ,   0.        ],
       [ 21.        ,  34.375     ,   0.        ],
       [ 41.        ,  19.5       ,   0.        ],
       [ 29.78590426,   7.225     ,   1.        ],
       [ 25.        ,  55.4417    ,   0.        ],
       [  0.92      , 151.55      ,   0.        ],
       [ 44.        ,  26.        ,   0.        ],
       [ 19.        ,  26.        ,   0.        ],
       [ 30.        ,  56.9292    ,   0.        ],
       [ 20.        ,   9.5       ,   0.        ],
       [  5.        ,  12.475     ,   0.        ],
       [  4.        ,  39.        ,   0.        ],
       [ 29.78590426,  16.1       ,   1.        ],
       [ 38.        ,   0.        ,   0.        ],
       [ 28.        ,  22.525     ,   0.        ],
       [ 29.78590426,  30.        ,   1.        ],
       [ 29.        ,   7.775     ,   0.        ],
       [ 49.        ,  89.1042    ,   0.        ],
       [ 19.        ,  14.5       ,   0.        ],
       [ 18.        , 262.375     ,   0.        ],
       [ 31.        ,  26.25      ,   0.        ],
       [ 27.        ,   7.7958    ,   0.        ],
       [ 36.        , 120.        ,   0.        ],
       [  8.        ,  36.75      ,   0.        ],
       [  2.        ,  21.075     ,   0.        ],
       [ 63.        ,  77.9583    ,   0.        ],
       [ 31.        ,   7.75      ,   0.        ],
       [ 29.78590426,   0.        ,   1.        ],
       [ 25.        ,  13.        ,   0.        ],
       [ 20.5       ,   7.25      ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 64.        , 263.        ,   0.        ],
       [ 19.        ,  26.        ,   0.        ],
       [ 18.        ,   7.775     ,   0.        ],
       [ 29.78590426,   0.        ,   1.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 11.        ,  18.7875    ,   0.        ],
       [ 15.        ,  14.4542    ,   0.        ],
       [ 22.        ,  55.        ,   0.        ],
       [ 50.        ,  13.        ,   0.        ],
       [ 28.        ,  14.4       ,   0.        ],
       [ 39.        ,  13.        ,   0.        ],
       [ 29.78590426,   8.05      ,   1.        ],
       [ 39.        ,   7.925     ,   0.        ],
       [ 24.        ,  16.1       ,   0.        ],
       [ 23.        ,   7.925     ,   0.        ],
       [ 17.        ,  57.        ,   0.        ],
       [ 44.        ,  26.        ,   0.        ],
       [ 23.        ,  13.7917    ,   0.        ],
       [ 29.78590426,  26.55      ,   1.        ],
       [ 52.        ,  78.2667    ,   0.        ],
       [ 24.5       ,   8.05      ,   0.        ],
       [ 55.5       ,   8.05      ,   0.        ],
       [ 18.        ,   7.7958    ,   0.        ],
       [ 18.        ,  13.        ,   0.        ],
       [ 45.        ,  83.475     ,   0.        ],
       [ 31.        ,  18.        ,   0.        ],
       [ 30.5       ,   8.05      ,   0.        ],
       [ 42.        ,   8.4042    ,   0.        ],
       [ 29.78590426,   7.75      ,   1.        ],
       [ 36.        ,   7.4958    ,   0.        ],
       [ 34.        ,  26.55      ,   0.        ],
       [ 54.        ,  78.2667    ,   0.        ],
       [ 15.        ,   8.0292    ,   0.        ],
       [ 25.        ,   7.775     ,   0.        ],
       [ 26.        ,  30.        ,   0.        ],
       [ 29.78590426,   8.1125    ,   1.        ],
       [ 19.        ,   8.05      ,   0.        ],
       [ 29.        ,   7.8958    ,   0.        ],
       [ 19.        ,  30.        ,   0.        ],
       [ 33.        ,  90.        ,   0.        ],
       [ 36.        ,  24.15      ,   0.        ],
       [ 29.78590426,   7.775     ,   1.        ],
       [ 35.        , 512.3292    ,   0.        ],
       [ 22.        ,   7.25      ,   0.        ],
       [ 29.78590426,  16.1       ,   1.        ],
       [ 18.        ,   7.4958    ,   0.        ],
       [ 28.        ,  26.        ,   0.        ],
       [ 22.        ,   7.25      ,   0.        ],
       [ 24.        ,   8.05      ,   0.        ],
       [ 22.        ,   9.        ,   0.        ],
       [ 29.78590426,  69.55      ,   1.        ],
       [ 26.        ,   7.8958    ,   0.        ],
       [ 29.        ,  10.4625    ,   0.        ]])

In [67]:
x_test.sample(10)

      Age     Fare  Age_na
743  24.0  16.1000     0.0
109   NaN  24.1500     1.0
382  32.0   7.9250     0.0
272  41.0  19.5000     0.0
702  18.0  14.4542     0.0
386   1.0  46.9000     0.0
67   19.0   8.1583     0.0
652  21.0   8.4333     0.0
68   17.0   7.9250     0.0
786  18.0   7.4958     0.0

In [59]:
si = SimpleImputer() #to fill the missing values in the age column

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [61]:
clf = LogisticRegression()
clf.fit(x_train_trf2 , y_train)
y_pred2 = clf.predict(x_test_trf2)

In [62]:
accuracy_score(y_test, y_pred2)

0.6312849162011173

In [63]:
x_test_trf2

array([[ 42.        ,  26.2875    ,   0.        ],
       [ 21.        ,   8.05      ,   0.        ],
       [ 24.        ,  65.        ,   0.        ],
       [ 28.        ,  56.4958    ,   0.        ],
       [ 17.        ,   7.925     ,   0.        ],
       [ 30.        ,   7.8958    ,   0.        ],
       [ 80.        ,  30.        ,   0.        ],
       [ 25.        ,   7.25      ,   0.        ],
       [ 50.        , 133.65      ,   0.        ],
       [ 25.        ,  26.        ,   0.        ],
       [ 35.        ,  26.        ,   0.        ],
       [ 35.        ,  90.        ,   0.        ],
       [ 55.        ,  16.        ,   0.        ],
       [ 29.78590426,  56.4958    ,   1.        ],
       [ 29.78590426,  56.4958    ,   1.        ],
       [ 19.        ,   7.8542    ,   0.        ],
       [ 29.78590426,  15.2458    ,   1.        ],
       [ 49.        ,   0.        ,   0.        ],
       [ 18.        ,  14.4542    ,   0.        ],
       [ 65.        ,   7.75      ,   0.        ],
       [ 18.        , 108.9       ,   0.        ],
       [ 29.78590426,  22.3583    ,   1.        ],
       [ 16.        ,  18.        ,   0.        ],
       [ 21.        ,   9.825     ,   0.        ],
       [ 19.        ,   6.75      ,   0.        ],
       [  1.        ,  11.1333    ,   0.        ],
       [ 50.        ,  10.5       ,   0.        ],
       [ 37.        ,  53.1       ,   0.        ],
       [ 28.        ,   9.5       ,   0.        ],
       [ 54.        ,  14.        ,   0.        ],
       [ 20.        ,   7.925     ,   0.        ],
       [ 36.        ,   0.        ,   0.        ],
       [  6.        ,  31.275     ,   0.        ],
       [ 29.78590426,  50.        ,   1.        ],
       [ 40.        ,  31.        ,   0.        ],
       [ 26.        ,  16.1       ,   0.        ],
       [ 30.        ,  93.5       ,   0.        ],
       [  1.        ,  46.9       ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 35.        ,  10.5       ,   0.        ],
       [ 38.        ,   7.05      ,   0.        ],
       [ 44.        ,  16.1       ,   0.        ],
       [ 22.        ,   7.75      ,   0.        ],
       [ 18.        ,   6.4958    ,   0.        ],
       [ 21.        ,   8.4333    ,   0.        ],
       [ 29.78590426, 227.525     ,   1.        ],
       [ 21.        ,  77.9583    ,   0.        ],
       [ 29.78590426,   8.6625    ,   1.        ],
       [ 22.        ,   7.225     ,   0.        ],
       [ 27.        ,  10.5       ,   0.        ],
       [ 29.78590426,   8.05      ,   1.        ],
       [ 51.        ,  26.55      ,   0.        ],
       [ 28.        ,  33.        ,   0.        ],
       [ 47.        ,  38.5       ,   0.        ],
       [ 32.        ,  10.5       ,   0.        ],
       [ 48.        ,  52.        ,   0.        ],
       [ 10.        ,  24.15      ,   0.        ],
       [ 21.        ,   8.6625    ,   0.        ],
       [ 51.        ,   7.0542    ,   0.        ],
       [ 32.        ,   7.925     ,   0.        ],
       [ 42.        ,  13.        ,   0.        ],
       [  2.        ,  26.        ,   0.        ],
       [ 35.        ,   8.05      ,   0.        ],
       [ 29.78590426,   7.25      ,   1.        ],
       [  2.        ,  10.4625    ,   0.        ],
       [ 33.        ,   9.5       ,   0.        ],
       [ 48.        ,  25.9292    ,   0.        ],
       [ 55.        ,  30.5       ,   0.        ],
       [  1.        ,  39.6875    ,   0.        ],
       [ 17.        ,   7.0542    ,   0.        ],
       [ 24.        ,  15.85      ,   0.        ],
       [ 74.        ,   7.775     ,   0.        ],
       [ 29.78590426,  24.15      ,   1.        ],
       [ 28.        ,   7.7958    ,   0.        ],
       [ 26.        ,   7.8542    ,   0.        ],
       [  1.        ,  39.        ,   0.        ],
       [ 18.        ,   8.05      ,   0.        ],
       [  3.        ,  26.        ,   0.        ],
       [ 48.        ,  39.6       ,   0.        ],
       [ 32.        ,  56.4958    ,   0.        ],
       [ 19.        ,  91.0792    ,   0.        ],
       [ 29.78590426,  42.4       ,   1.        ],
       [ 70.        ,  10.5       ,   0.        ],
       [ 34.        ,  26.        ,   0.        ],
       [ 39.        , 110.8833    ,   0.        ],
       [ 17.        ,  10.5       ,   0.        ],
       [ 38.        ,   8.6625    ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 30.        ,  21.        ,   0.        ],
       [ 28.        ,  13.        ,   0.        ],
       [ 29.78590426,   7.725     ,   1.        ],
       [ 19.        ,   8.1583    ,   0.        ],
       [ 29.        ,   7.75      ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 44.        ,   7.925     ,   0.        ],
       [ 22.        ,  41.5792    ,   0.        ],
       [ 21.        ,  34.375     ,   0.        ],
       [ 41.        ,  19.5       ,   0.        ],
       [ 29.78590426,   7.225     ,   1.        ],
       [ 25.        ,  55.4417    ,   0.        ],
       [  0.92      , 151.55      ,   0.        ],
       [ 44.        ,  26.        ,   0.        ],
       [ 19.        ,  26.        ,   0.        ],
       [ 30.        ,  56.9292    ,   0.        ],
       [ 20.        ,   9.5       ,   0.        ],
       [  5.        ,  12.475     ,   0.        ],
       [  4.        ,  39.        ,   0.        ],
       [ 29.78590426,  16.1       ,   1.        ],
       [ 38.        ,   0.        ,   0.        ],
       [ 28.        ,  22.525     ,   0.        ],
       [ 29.78590426,  30.        ,   1.        ],
       [ 29.        ,   7.775     ,   0.        ],
       [ 49.        ,  89.1042    ,   0.        ],
       [ 19.        ,  14.5       ,   0.        ],
       [ 18.        , 262.375     ,   0.        ],
       [ 31.        ,  26.25      ,   0.        ],
       [ 27.        ,   7.7958    ,   0.        ],
       [ 36.        , 120.        ,   0.        ],
       [  8.        ,  36.75      ,   0.        ],
       [  2.        ,  21.075     ,   0.        ],
       [ 63.        ,  77.9583    ,   0.        ],
       [ 31.        ,   7.75      ,   0.        ],
       [ 29.78590426,   0.        ,   1.        ],
       [ 25.        ,  13.        ,   0.        ],
       [ 20.5       ,   7.25      ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 64.        , 263.        ,   0.        ],
       [ 19.        ,  26.        ,   0.        ],
       [ 18.        ,   7.775     ,   0.        ],
       [ 29.78590426,   0.        ,   1.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 11.        ,  18.7875    ,   0.        ],
       [ 15.        ,  14.4542    ,   0.        ],
       [ 22.        ,  55.        ,   0.        ],
       [ 50.        ,  13.        ,   0.        ],
       [ 28.        ,  14.4       ,   0.        ],
       [ 39.        ,  13.        ,   0.        ],
       [ 29.78590426,   8.05      ,   1.        ],
       [ 39.        ,   7.925     ,   0.        ],
       [ 24.        ,  16.1       ,   0.        ],
       [ 23.        ,   7.925     ,   0.        ],
       [ 17.        ,  57.        ,   0.        ],
       [ 44.        ,  26.        ,   0.        ],
       [ 23.        ,  13.7917    ,   0.        ],
       [ 29.78590426,  26.55      ,   1.        ],
       [ 52.        ,  78.2667    ,   0.        ],
       [ 24.5       ,   8.05      ,   0.        ],
       [ 55.5       ,   8.05      ,   0.        ],
       [ 18.        ,   7.7958    ,   0.        ],
       [ 18.        ,  13.        ,   0.        ],
       [ 45.        ,  83.475     ,   0.        ],
       [ 31.        ,  18.        ,   0.        ],
       [ 30.5       ,   8.05      ,   0.        ],
       [ 42.        ,   8.4042    ,   0.        ],
       [ 29.78590426,   7.75      ,   1.        ],
       [ 36.        ,   7.4958    ,   0.        ],
       [ 34.        ,  26.55      ,   0.        ],
       [ 54.        ,  78.2667    ,   0.        ],
       [ 15.        ,   8.0292    ,   0.        ],
       [ 25.        ,   7.775     ,   0.        ],
       [ 26.        ,  30.        ,   0.        ],
       [ 29.78590426,   8.1125    ,   1.        ],
       [ 19.        ,   8.05      ,   0.        ],
       [ 29.        ,   7.8958    ,   0.        ],
       [ 19.        ,  30.        ,   0.        ],
       [ 33.        ,  90.        ,   0.        ],
       [ 36.        ,  24.15      ,   0.        ],
       [ 29.78590426,   7.775     ,   1.        ],
       [ 35.        , 512.3292    ,   0.        ],
       [ 22.        ,   7.25      ,   0.        ],
       [ 29.78590426,  16.1       ,   1.        ],
       [ 18.        ,   7.4958    ,   0.        ],
       [ 28.        ,  26.        ,   0.        ],
       [ 22.        ,   7.25      ,   0.        ],
       [ 24.        ,   8.05      ,   0.        ],
       [ 22.        ,   9.        ,   0.        ],
       [ 29.78590426,  69.55      ,   1.        ],
       [ 26.        ,   7.8958    ,   0.        ],
       [ 29.        ,  10.4625    ,   0.        ]])