In [1]:
#with n without binarization

In [2]:
import numpy as np
import pandas as pd

In [1]:
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import  cross_val_score

In [4]:
df = pd.read_csv('../data/titanic_train.csv' , usecols =['Age' , 'Fare', 'Parch', 'Survived', 'SibSp'])

In [5]:
df.dropna(inplace = True) #droping rows with missing values

In [6]:
df.head()

   Survived   Age  SibSp  Parch     Fare
0         0  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         1  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         0  35.0      0      0   8.0500

In [7]:
df['Family'] = df['SibSp'] + df['Parch']

In [8]:
df.head()

   Survived   Age  SibSp  Parch     Fare  Family
0         0  22.0      1      0   7.2500       1
1         1  38.0      1      0  71.2833       1
2         1  26.0      0      0   7.9250       0
3         1  35.0      1      0  53.1000       1
4         0  35.0      0      0   8.0500       0

In [9]:
df.drop(columns = ['Parch', 'SibSp'] , inplace = True)

In [10]:
df.sample(10)

     Survived   Age      Fare  Family
809         1  33.0   53.1000       1
98          1  34.0   23.0000       1
834         0  18.0    8.3000       0
559         1  36.0   17.4000       1
268         1  58.0  153.4625       1
569         1  32.0    7.8542       0
623         0  21.0    7.8542       0
608         1  22.0   41.5792       3
746         0  16.0   20.2500       2
192         1  19.0    7.8542       1

In [11]:
x = df.drop(columns = ['Survived'])
y = df['Survived']

In [12]:
x_train , x_test , y_train, y_test = train_test_split(df.drop(columns = ['Survived']), df['Survived'] ,test_size = 0.2, random_state = 42)

In [13]:
x_train.head()

      Age     Fare  Family
328  31.0  20.5250       2
73   26.0  14.4542       1
253  30.0  16.1000       1
719  33.0   7.7750       0
666  25.0  13.0000       0

In [14]:
#without binarization
clf = DecisionTreeClassifier()

clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)

accuracy_score(y_test, y_pred)

0.6503496503496503

In [15]:
np.mean(cross_val_score(DecisionTreeClassifier(), x, y , cv = 10 , scoring = 'accuracy'))

np.float64(0.6443075117370892)

In [16]:
#applying binarization

from sklearn.preprocessing import Binarizer

In [17]:
trf = ColumnTransformer([
    ('bin' , Binarizer(copy = False),['Family'])
], remainder= 'passthrough')

In [18]:
x_train_trf = trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)

In [19]:
pd.DataFrame(x_train_trf , columns = ['Family' ,'Age' , 'Fare'])

     Family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [20]:
clf = DecisionTreeClassifier()
clf.fit(x_train_trf, y_train)
y_pred2 = clf.predict(x_test_trf)

accuracy_score(y_test , y_pred2)

0.5944055944055944

In [21]:
x_trf = trf.fit_transform(x)
np.mean(cross_val_score(DecisionTreeClassifier(), x, y , cv = 10 , scoring = 'accuracy'))

np.float64(0.6541275430359937)