In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info() #to work on the date time, date time column dtype shouldnt be an object and should be date &time

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

**WORKING WITH DATES**

In [7]:
#converting to date time data type
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1. Extract Year

In [12]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

2. Extract month

In [13]:
date['date_month'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [14]:
date['date_month'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year date_month
0 2019-12-10        5628       25       3       2019   December
1 2018-08-15        3646       14     157       2018     August
2 2018-10-23        1859       25       1       2018    October
3 2019-08-17        7292       25       1       2019     August
4 2019-01-06        4344       25       3       2019    January

3. Extract days

In [15]:
date['date_day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year date_month  date_day
0 2019-12-10        5628       25       3       2019   December        10
1 2018-08-15        3646       14     157       2018     August        15
2 2018-10-23        1859       25       1       2018    October        23
3 2019-08-17        7292       25       1       2019     August        17
4 2019-01-06        4344       25       3       2019    January         6

In [16]:
#day of the week
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_dow
0,2019-12-10,5628,25,3,2019,December,10,1
1,2018-08-15,3646,14,157,2018,August,15,2
2,2018-10-23,1859,25,1,2018,October,23,1
3,2019-08-17,7292,25,1,2019,August,17,5
4,2019-01-06,4344,25,3,2019,January,6,6

In [19]:
#day of week - name
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns = ['product_id','city_id', 'orders']).head()

        date  date_year date_month  date_day  date_dow date_dow_name
0 2019-12-10       2019   December        10         1       Tuesday
1 2018-08-15       2018     August        15         2     Wednesday
2 2018-10-23       2018    October        23         1       Tuesday
3 2019-08-17       2019     August        17         5      Saturday
4 2019-01-06       2019    January         6         6        Sunday

In [21]:
#is weekend ?
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Saturday','Sunday']),1,0)
date.drop(columns = ['product_id', 'city_id','orders']).head()

,date,date_year,date_month,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,December,10,1,Tuesday,0
1,2018-08-15,2018,August,15,2,Wednesday,0
2,2018-10-23,2018,October,23,1,Tuesday,0
3,2019-08-17,2019,August,17,5,Saturday,1
4,2019-01-06,2019,January,6,6,Sunday,1

In [24]:
#extract week of the year
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns = ['product_id', 'city_id','orders']).head()

,date,date_year,date_month,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,December,10,1,Tuesday,0,50
1,2018-08-15,2018,August,15,2,Wednesday,0,33
2,2018-10-23,2018,October,23,1,Tuesday,0,43
3,2019-08-17,2019,August,17,5,Saturday,1,33
4,2019-01-06,2019,January,6,6,Sunday,1,1

In [26]:
#extratc semester
date['quarter'] = date['date'].dt.quarter
date['semester']= np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns = ['product_id', 'city_id','orders']).head()

,date,date_year,date_month,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,January,6,6,Sunday,1,1,1,1

time elapsed bw two dates

In [27]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 6, 24, 16, 53, 24, 490789)

In [28]:
today - date['date']

0     2388 days 16:53:24.490789
1     2870 days 16:53:24.490789
2     2801 days 16:53:24.490789
3     2503 days 16:53:24.490789
4     2726 days 16:53:24.490789
                 ...
995   2816 days 16:53:24.490789
996   2757 days 16:53:24.490789
997   2605 days 16:53:24.490789
998   2670 days 16:53:24.490789
999   2444 days 16:53:24.490789
Name: date, Length: 1000, dtype: timedelta64[ns]

months passed

In [30]:
np.round((today-date['date'])/np.timedelta64(1, 'm'), 0)

0      3439733.0
1      4133813.0
2      4034453.0
3      3605333.0
4      3926453.0
         ...
995    4056053.0
996    3971093.0
997    3752213.0
998    3845813.0
999    3520373.0
Name: date, Length: 1000, dtype: float64

In [31]:
time

                   date                                                msg
0   2013-12-15 00:50:00                           ищу на сегодня мужика 37
1   2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2   2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3   2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4   2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                  ...                                                ...
995 2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996 2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997 2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998 2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999 2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [10]:
time['date'] = pd.to_datetime(time['date'])

In [11]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [32]:
time['date'] = pd.to_datetime(time['date'])

In [33]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [34]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

Extract time part

In [35]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [36]:
#time difference
today - time['date']

0     4574 days 16:03:24.490789
1     4438 days 17:13:24.490789
2     4924 days 16:32:24.490789
3     4226 days 16:22:24.490789
4     4623 days 17:42:24.490789
                 ...
995   5213 days 16:03:24.490789
996   4534 days 17:39:24.490789
997   4999 days 17:16:24.490789
998   5115 days 17:19:24.490789
999   4387 days 17:28:24.490789
Name: date, Length: 1000, dtype: timedelta64[ns]

In [43]:
#in seconds
(today - time['date'])/np.timedelta64(1, 's')

0      3.952514e+08
1      3.835052e+08
2      4.254931e+08
3      3.651853e+08
4      3.994909e+08
           ...
995    4.504610e+08
996    3.918012e+08
997    4.319758e+08
998    4.419984e+08
999    3.790997e+08
Name: date, Length: 1000, dtype: float64