One Hot Encoding(for nominal data)

if we are given data as

color        target
yellow         0
y              1
blue            1
y              0
red             1
y               0
r
r
y
b

In [1]:
#we create n cols and represent each variable as vector . for yellow [1,0,0] red [0, 0,1] blue is [0,1,0].



#then we remove 1 of the cols. and can still represent all the colours .
# Concept ?
#MULTICOLINEARLITY

In [2]:
#OHE using most frequent variables.

#we make cols for most frequent variables and put the less frequent ones  into a single 'others' columns.

In [3]:
import numpy as np
import pandas as pd

In [4]:
dff = pd.read_csv('usedcar.csv')

In [5]:
dff.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen..."
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D..."
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010..."
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol"

In [6]:
df = dff[['Brand' , 'kmDriven', 'FuelType', 'Owner' ,'Age']]

In [7]:
df.sample(7)

              Brand    kmDriven FuelType   Owner  Age
2621         Toyota  170,000 km   Diesel   first    7
5862          Honda   92,000 km   Petrol  second    7
2342        Renault  77000.0 km   Petrol   first    8
8274  Maruti Suzuki   94,000 km   Diesel   first    6
325   Maruti Suzuki   90,000 km   Diesel   first    5
4345          Honda   39,000 km   Petrol  second    8
4296           Audi   65,000 km   Diesel  second    7

In [8]:
df.shape

(9582, 5)

In [9]:
df['Brand'].value_counts()

Brand
Maruti Suzuki    2720
Hyundai          1529
Honda             802
Toyota            777
Mahindra          560
Mercedes-Benz     402
Tata              389
BMW               342
Volkswagen        318
Audi              264
Ford              245
Renault           240
Skoda             183
Kia               161
Chevrolet          89
MG                 80
Nissan             75
Jeep               74
Land Rover         71
Volvo              48
Mini               41
Jaguar             34
Porsche            24
Fiat               22
Datsun             22
Lexus              20
Mitsubishi         18
Isuzu              10
Force               6
Ambassador          3
Rolls-Royce         2
Bajaj               2
Opel                2
Ssangyong           2
Aston Martin        1
ICML                1
Ashok               1
Bentley             1
Maserati            1
Name: count, dtype: int64

In [10]:
df['Brand'].nunique() #there are 39 different brands

39

In [11]:
df['FuelType'].nunique()

3

In [12]:
df['FuelType'].value_counts()

FuelType
Diesel        3840
Petrol        3822
Hybrid/CNG    1920
Name: count, dtype: int64

In [13]:
df['Owner'].value_counts()

Owner
first     4800
second    4782
Name: count, dtype: int64

**1.OHE using pandas**

In [14]:
pd.get_dummies(df, columns = ['FuelType' , 'Owner'] , dtype = int) #new cols have been created.

,Brand,kmDriven,Age,FuelType_Diesel,FuelType_Hybrid/CNG,FuelType_Petrol,Owner_first,Owner_second
0,Honda,"98,000 km",23,0,0,1,0,1
1,Toyota,190000.0 km,15,1,0,0,0,1
2,Volkswagen,"77,246 km",14,1,0,0,1,0
3,Maruti Suzuki,"83,500 km",7,1,0,0,0,1
4,Maruti Suzuki,"45,000 km",5,0,0,1,1,0
...,...,...,...,...,...,...,...,...
9577,Skoda,"105,904 km",10,1,0,0,0,1
9578,Maruti Suzuki,"55,000 km",4,0,1,0,1,0
9579,Maruti Suzuki,"92,000 km",11,1,0,0,1,0
9580,Hyundai,"72,000 km",5,0,0,1,1,0
9581,Hyundai,"83,228 km",3,0,0,1,0,1

the above changes are not permanent

In [15]:
df.head()

           Brand     kmDriven FuelType   Owner  Age
0          Honda    98,000 km   Petrol  second   23
1         Toyota  190000.0 km   Diesel  second   15
2     Volkswagen    77,246 km   Diesel   first   14
3  Maruti Suzuki    83,500 km   Diesel  second    7
4  Maruti Suzuki    45,000 km   Petrol   first    5

2. Solving multicollinearity
K-1 ONEHOT ENCODING

In [16]:
pd.get_dummies(df, columns = ['FuelType', 'Owner'],dtype = int,drop_first = True)

,Brand,kmDriven,Age,FuelType_Hybrid/CNG,FuelType_Petrol,Owner_second
0,Honda,"98,000 km",23,0,1,1
1,Toyota,190000.0 km,15,0,0,1
2,Volkswagen,"77,246 km",14,0,0,0
3,Maruti Suzuki,"83,500 km",7,0,0,1
4,Maruti Suzuki,"45,000 km",5,0,1,0
...,...,...,...,...,...,...
9577,Skoda,"105,904 km",10,0,0,1
9578,Maruti Suzuki,"55,000 km",4,1,0,0
9579,Maruti Suzuki,"92,000 km",11,0,0,0
9580,Hyundai,"72,000 km",5,0,1,0
9581,Hyundai,"83,228 km",3,0,1,1

3. OneHotEncoding using Sklearn

In [17]:
from sklearn.model_selection import train_test_split
x_train ,x_test , y_train ,  y_test = train_test_split(df.iloc[: ,0:4] , df.iloc[:, -1] ,test_size = 0.2 , random_state = 0)

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
ohe = OneHotEncoder(drop = 'first'  , dtype = np.int32)

In [20]:
x_train

              Brand    kmDriven    FuelType   Owner
5337  Mercedes-Benz  45000.0 km      Petrol  second
2735         Toyota  125,000 km      Diesel  second
6075  Maruti Suzuki   66,000 km      Petrol  second
4068        Hyundai   79,000 km  Hybrid/CNG  second
6616        Hyundai   56,000 km      Diesel   first
...             ...         ...         ...     ...
7891        Hyundai   80,000 km      Petrol   first
9225  Maruti Suzuki   50,000 km      Petrol   first
4859        Hyundai   43,000 km      Petrol  second
3264  Mercedes-Benz   16,000 km      Diesel   first
2732            BMW   39,000 km      Diesel  second

[7665 rows x 4 columns]

In [21]:
x_train_new = ohe.fit_transform(x_train[['FuelType', 'Owner']])

In [22]:
x_train_new =ohe.fit_transform(x_train[['FuelType' , 'Owner']]).toarray()
#has become a sparse matrix

In [37]:
x_test_new = ohe.fit_transform(x_test[['FuelType' , 'Owner']]).toarray()

In [36]:
x_test_new

array([[0., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 1., 1.],
       [0., 0., 1.],
       [0., 1., 0.]], shape=(1917, 3))

In [38]:
x_train_new #this is jus for fuel type and owner. I still need to append the column brand and kmdriven to this one.

array([['Mercedes-Benz', '45000.0 km', 0.0, 1.0, 1.0],
       ['Toyota', '125,000 km', 0.0, 0.0, 1.0],
       ['Maruti Suzuki', '66,000 km', 0.0, 1.0, 1.0],
       ...,
       ['Hyundai', '43,000 km', 0.0, 1.0, 1.0],
       ['Mercedes-Benz', '16,000 km', 0.0, 0.0, 0.0],
       ['BMW', '39,000 km', 0.0, 0.0, 1.0]], shape=(7665, 5), dtype=object)

In [40]:
x_train[['Brand', 'kmDriven']].values #got it in the array form.

array([['Mercedes-Benz', '45000.0 km'],
       ['Toyota', '125,000 km'],
       ['Maruti Suzuki', '66,000 km'],
       ...,
       ['Hyundai', '43,000 km'],
       ['Mercedes-Benz', '16,000 km'],
       ['BMW', '39,000 km']], shape=(7665, 2), dtype=object)

In [27]:
np.hstack((x_train[['Brand', 'kmDriven']].values  , x_train_new))
#both the numpy arrays have been stacked horizontally.

array([['Mercedes-Benz', '45000.0 km', 0.0, 1.0, 1.0],
       ['Toyota', '125,000 km', 0.0, 0.0, 1.0],
       ['Maruti Suzuki', '66,000 km', 0.0, 1.0, 1.0],
       ...,
       ['Hyundai', '43,000 km', 0.0, 1.0, 1.0],
       ['Mercedes-Benz', '16,000 km', 0.0, 0.0, 0.0],
       ['BMW', '39,000 km', 0.0, 0.0, 1.0]], shape=(7665, 5), dtype=object)

In [41]:
x_train_new

array([['Mercedes-Benz', '45000.0 km', 0.0, 1.0, 1.0],
       ['Toyota', '125,000 km', 0.0, 0.0, 1.0],
       ['Maruti Suzuki', '66,000 km', 0.0, 1.0, 1.0],
       ...,
       ['Hyundai', '43,000 km', 0.0, 1.0, 1.0],
       ['Mercedes-Benz', '16,000 km', 0.0, 0.0, 0.0],
       ['BMW', '39,000 km', 0.0, 0.0, 1.0]], shape=(7665, 5), dtype=object)

In [29]:
np.hstack((x_train[['Brand' ,'kmDriven']].values , x_train_new)).shape

(7665, 5)

In [30]:
x_train_new = np.hstack((x_train[['Brand' ,'kmDriven']].values , x_train_new))

In [31]:
x_train_new.shape

(7665, 5)

In [32]:
df.iloc[: , 0:4]

              Brand     kmDriven    FuelType   Owner
0             Honda    98,000 km      Petrol  second
1            Toyota  190000.0 km      Diesel  second
2        Volkswagen    77,246 km      Diesel   first
3     Maruti Suzuki    83,500 km      Diesel  second
4     Maruti Suzuki    45,000 km      Petrol   first
...             ...          ...         ...     ...
9577          Skoda   105,904 km      Diesel  second
9578  Maruti Suzuki    55,000 km  Hybrid/CNG   first
9579  Maruti Suzuki    92,000 km      Diesel   first
9580        Hyundai    72,000 km      Petrol   first
9581        Hyundai    83,228 km      Petrol  second

[9582 rows x 4 columns]

4. OHE with top categories

In [44]:
x_train_new.tolist()

[['Mercedes-Benz', '45000.0 km', 0.0, 1.0, 1.0],
 ['Toyota', '125,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '66,000 km', 0.0, 1.0, 1.0],
 ['Hyundai', '79,000 km', 1.0, 0.0, 1.0],
 ['Hyundai', '56,000 km', 0.0, 0.0, 0.0],
 ['Hyundai', '42,000 km', 0.0, 1.0, 1.0],
 ['Kia', '65,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '31,000 km', 0.0, 1.0, 1.0],
 ['Honda', '97,422 km', 0.0, 0.0, 1.0],
 ['Mahindra', '69,120 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '48,963 km', 1.0, 0.0, 0.0],
 ['Tata', '45,000 km', 0.0, 0.0, 1.0],
 ['Toyota', '191,000 km', 0.0, 0.0, 0.0],
 ['BMW', '50,000 km', 0.0, 0.0, 1.0],
 ['Hyundai', '19,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '130,000 km', 0.0, 0.0, 0.0],
 ['Tata', '88,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '55,000 km', 0.0, 1.0, 0.0],
 ['Tata', '52,000 km', 0.0, 1.0, 0.0],
 ['Honda', '71,000 km', 0.0, 1.0, 1.0],
 ['Mahindra', '80,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '101,110 km', 1.0, 0.0, 1.0],
 ['Mahindra', '85,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '49,000 km', 0.0, 1.0, 0.0],
 ['Jaguar', '76000.0 km', 0.0, 0.0, 1.0],
 ['Mercedes-Benz', '25,000 km', 0.0, 0.0, 0.0],
 ['Volkswagen', '85,000 km', 0.0, 0.0, 0.0],
 ['BMW', '86,000 km', 0.0, 0.0, 1.0],
 ['Chevrolet', '116,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '90,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '82,000 km', 1.0, 0.0, 1.0],
 ['Toyota', '32,000 km', 0.0, 1.0, 0.0],
 ['Mahindra', '87,000 km', 0.0, 0.0, 0.0],
 ['Hyundai', '44,500 km', 0.0, 1.0, 1.0],
 ['Jaguar', '65,000 km', 0.0, 0.0, 0.0],
 ['Toyota', '108,000 km', 0.0, 1.0, 0.0],
 ['Volkswagen', '102,000 km', 0.0, 1.0, 1.0],
 ['Tata', '81,000 km', 0.0, 0.0, 1.0],
 ['Honda', '35,000 km', 0.0, 1.0, 0.0],
 ['Toyota', '86,000 km', 0.0, 0.0, 1.0],
 ['Hyundai', '170,000 km', 0.0, 0.0, 1.0],
 ['Honda', '93,000 km', 1.0, 0.0, 0.0],
 ['Hyundai', '120,000 km', 1.0, 0.0, 0.0],
 ['Maruti Suzuki', '64,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '115,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '85,000 km', 1.0, 0.0, 1.0],
 ['Maruti Suzuki', '85,000 km', 1.0, 0.0, 0.0],
 ['Maruti Suzuki', '8,254 km', 0.0, 1.0, 0.0],
 ['Mercedes-Benz', '36,250 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '70,150 km', 1.0, 0.0, 1.0],
 ['Audi', '51,000 km', 0.0, 1.0, 1.0],
 ['Toyota', '50,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '5,000 km', 1.0, 0.0, 0.0],
 ['MG', '65,000 km', 0.0, 1.0, 0.0],
 ['Mercedes-Benz', '6,000 km', 0.0, 0.0, 0.0],
 ['Volkswagen', '107,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '49,000 km', 0.0, 1.0, 0.0],
 ['Mahindra', '79,000 km', 0.0, 0.0, 0.0],
 ['BMW', '7000.0 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '105,000 km', 1.0, 0.0, 1.0],
 ['Toyota', '180,555 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '84,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '51,000 km', 1.0, 0.0, 0.0],
 ['Maruti Suzuki', '142,000 km', 0.0, 1.0, 0.0],
 ['Hyundai', '13,262 km', 0.0, 1.0, 0.0],
 ['Honda', '83,568 km', 0.0, 0.0, 1.0],
 ['Lexus', '24,000 km', 0.0, 0.0, 0.0],
 ['Ford', '610,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '81,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '68,000 km', 1.0, 0.0, 0.0],
 ['Audi', '45,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '34,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '0 km', 1.0, 0.0, 1.0],
 ['Maruti Suzuki', '94,000 km', 1.0, 0.0, 0.0],
 ['Maruti Suzuki', '114,000 km', 1.0, 0.0, 1.0],
 ['Kia', '34,000 km', 1.0, 0.0, 0.0],
 ['Hyundai', '103,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '34,500 km', 0.0, 1.0, 1.0],
 ['Toyota', '155,000 km', 0.0, 0.0, 1.0],
 ['Toyota', '277,000 km', 0.0, 0.0, 0.0],
 ['Honda', '82,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '86000.0 km', 1.0, 0.0, 1.0],
 ['Volkswagen', '17000.0 km', 0.0, 1.0, 0.0],
 ['Mahindra', '101,000 km', 0.0, 0.0, 1.0],
 ['Audi', '72,000 km', 0.0, 0.0, 0.0],
 ['Tata', '46,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '65,999 km', 1.0, 0.0, 0.0],
 ['Maruti Suzuki', '80,000 km', 1.0, 0.0, 0.0],
 ['Kia', '72,000 km', 0.0, 0.0, 0.0],
 ['Ford', '110,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '75,000 km', 1.0, 0.0, 1.0],
 ['Skoda', '87,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '32,000 km', 0.0, 1.0, 0.0],
 ['Porsche', '56,000 km', 0.0, 0.0, 1.0],
 ['Volkswagen', '149000.0 km', 0.0, 1.0, 1.0],
 ['Honda', '98,000 km', 1.0, 0.0, 1.0],
 ['Maruti Suzuki', '90,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '71,000 km', 1.0, 0.0, 1.0],
 ['Maruti Suzuki', '98,130 km', 1.0, 0.0, 1.0],
 ['Audi', '42,000 km', 0.0, 0.0, 1.0],
 ['Hyundai', '68,000 km', 0.0, 0.0, 1.0],
 ['Ford', '45,000 km', 0.0, 1.0, 1.0],
 ['Renault', '27,500 km', 0.0, 1.0, 0.0],
 ['Hyundai', '44,000 km', 0.0, 1.0, 0.0],
 ['Honda', '67000.0 km', 0.0, 1.0, 1.0],
 ['Tata', '14,000 km', 0.0, 0.0, 0.0],
 ['Mercedes-Benz', '29,000 km', 0.0, 0.0, 0.0],
 ['Volkswagen', '76,654 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '22,000 km', 0.0, 1.0, 0.0],
 ['Renault', '87,000 km', 0.0, 0.0, 1.0],
 ['Honda', '66,147 km', 0.0, 1.0, 1.0],
 ['Porsche', '7,000 km', 0.0, 1.0, 0.0],
 ['Hyundai', '86,123 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '120,000 km', 0.0, 0.0, 1.0],
 ['Volkswagen', '140,000 km', 0.0, 0.0, 1.0],
 ['Ford', '75,000 km', 0.0, 0.0, 1.0],
 ['Hyundai', '55,000 km', 0.0, 1.0, 1.0],
 ['Hyundai', '85,000 km', 0.0, 0.0, 1.0],
 ['Mahindra', '42,000 km', 0.0, 0.0, 0.0],
 ['Volkswagen', '75,000 km', 0.0, 0.0, 0.0],
 ['Mercedes-Benz', '59001.0 km', 0.0, 0.0, 0.0],
 ['Mercedes-Benz', '42,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '68,000 km', 1.0, 0.0, 0.0],
 ['Tata', '39,000 km', 0.0, 0.0, 0.0],
 ['Honda', '103,000 km', 1.0, 0.0, 1.0],
 ['Maruti Suzuki', '100,000 km', 0.0, 1.0, 1.0],
 ['Hyundai', '41,973 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '199,600 km', 0.0, 0.0, 1.0],
 ['Toyota', '75,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '72,000 km', 0.0, 0.0, 1.0],
 ['Hyundai', '25 km', 1.0, 0.0, 1.0],
 ['Toyota', '71,000 km', 0.0, 0.0, 1.0],
 ['Volkswagen', '35,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '66,000 km', 1.0, 0.0, 1.0],
 ['Tata', '123,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '62,125 km', 1.0, 0.0, 1.0],
 ['Maruti Suzuki', '70,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '80,000 km', 0.0, 1.0, 0.0],
 ['Hyundai', '74,500 km', 0.0, 0.0, 0.0],
 ['Hyundai', '65,000 km', 0.0, 0.0, 0.0],
 ['Mahindra', '78,000 km', 0.0, 0.0, 0.0],
 ['Mercedes-Benz', '73,000 km', 0.0, 0.0, 1.0],
 ['Hyundai', '80,000 km', 0.0, 1.0, 1.0],
 ['Hyundai', '137,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '75,200 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '78,000 km', 0.0, 0.0, 1.0],
 ['Kia', '27,300 km', 0.0, 1.0, 1.0],
 ['Honda', '65,000 km', 0.0, 1.0, 0.0],
 ['Toyota', '110,000 km', 0.0, 0.0, 1.0],
 ['Hyundai', '65,606 km', 1.0, 0.0, 1.0],
 ['Tata', '12,600 km', 0.0, 1.0, 0.0],
 ['Honda', '20,000 km', 0.0, 1.0, 1.0],
 ['Audi', '73,930 km', 0.0, 0.0, 1.0],
 ['Hyundai', '55,000 km', 0.0, 1.0, 1.0],
 ['Hyundai', '57,000 km', 1.0, 0.0, 1.0],
 ['Mahindra', '88,500 km', 0.0, 0.0, 0.0],
 ['Ford', '140,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '74,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '51,000 km', 0.0, 1.0, 0.0],
 ['Hyundai', '8394.0 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '64,000 km', 0.0, 0.0, 0.0],
 ['Honda', '67000.0 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', nan, 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '37,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '80,000 km', 1.0, 0.0, 1.0],
 ['Maruti Suzuki', '37,000 km', 0.0, 1.0, 1.0],
 ['Tata', '50,000 km', 1.0, 0.0, 0.0],
 ['Mahindra', '123,000 km', 0.0, 0.0, 1.0],
 ['Skoda', '3,000 km', 0.0, 1.0, 0.0],
 ['MG', '45,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '62,217 km', 1.0, 0.0, 1.0],
 ['Toyota', '77000.0 km', 0.0, 0.0, 0.0],
 ['Toyota', '42,000 km', 0.0, 1.0, 0.0],
 ['Nissan', '70000.0 km', 0.0, 0.0, 0.0],
 ['Volkswagen', '61,000 km', 0.0, 1.0, 0.0],
 ['Toyota', '125,000 km', 0.0, 0.0, 1.0],
 ['Audi', '87,000 km', 0.0, 0.0, 1.0],
 ['Hyundai', '8,499 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '230 km', 0.0, 0.0, 0.0],
 ['Skoda', '40,000 km', 0.0, 1.0, 0.0],
 ['Mercedes-Benz', '41,000 km', 0.0, 1.0, 1.0],
 ['Hyundai', '120,000 km', 0.0, 1.0, 0.0],
 ['Tata', '10,000 km', 0.0, 1.0, 0.0],
 ['Kia', '48,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '58,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '78,000 km', 1.0, 0.0, 0.0],
 ['Skoda', '104,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '64,000 km', 1.0, 0.0, 1.0],
 ['Tata', '98,000 km', 0.0, 0.0, 0.0],
 ['Renault', '12,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '11,000 km', 0.0, 1.0, 0.0],
 ['Mahindra', '76,269 km', 0.0, 0.0, 1.0],
 ['Mercedes-Benz', '38,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '72000.0 km', 0.0, 1.0, 0.0],
 ['Mercedes-Benz', '51,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '76,000 km', 1.0, 0.0, 1.0],
 ['Honda', '89000.0 km', 0.0, 1.0, 1.0],
 ['Volkswagen', '121,000 km', 0.0, 0.0, 1.0],
 ['Toyota', '24,000 km', 0.0, 1.0, 0.0],
 ['Hyundai', '63,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '34,000 km', 1.0, 0.0, 0.0],
 ['Hyundai', '64,259 km', 1.0, 0.0, 1.0],
 ['Maruti Suzuki', '65,000 km', 0.0, 1.0, 0.0],
 ['MG', '39,652 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '67,000 km', 1.0, 0.0, 1.0],
 ['Mahindra', '100,003 km', 0.0, 0.0, 1.0],
 ['Ford', '40,860 km', 1.0, 0.0, 0.0],
 ['Hyundai', '30,000 km', 0.0, 0.0, 0.0],
 ['Honda', '49,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '68,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '39,000 km', 0.0, 1.0, 0.0],
 ['Honda', '124,000 km', 0.0, 0.0, 0.0],
 ['Hyundai', '76,000 km', 1.0, 0.0, 1.0],
 ['Hyundai', '82,000 km', 0.0, 1.0, 1.0],
 ['Audi', '57,000 km', 0.0, 1.0, 0.0],
 ['BMW', '74000.0 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '72,386 km', 1.0, 0.0, 0.0],
 ['Mercedes-Benz', '42,000 km', 0.0, 1.0, 1.0],
 ['Ford', '69,713 km', 0.0, 1.0, 1.0],
 ['Hyundai', '73,000 km', 0.0, 0.0, 0.0],
 ['Jaguar', '41,000 km', 0.0, 0.0, 0.0],
 ['Toyota', '151,000 km', 0.0, 0.0, 0.0],
 ['Toyota', '130,000 km', 0.0, 1.0, 1.0],
 ['Volkswagen', '72,900 km', 0.0, 0.0, 1.0],
 ['Toyota', '130,000 km', 0.0, 0.0, 0.0],
 ['Mercedes-Benz', '55,000 km', 0.0, 1.0, 0.0],
 ['Kia', '16,000 km', 0.0, 1.0, 0.0],
 ['Toyota', '62,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '68,350 km', 1.0, 0.0, 1.0],
 ['Honda', '96,000 km', 1.0, 0.0, 1.0],
 ['Toyota', '190,000 km', 0.0, 0.0, 1.0],
 ['Renault', '67,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '72,000 km', 0.0, 1.0, 1.0],
 ['Hyundai', '80,000 km', 1.0, 0.0, 0.0],
 ['Maruti Suzuki', '1,600 km', 0.0, 1.0, 0.0],
 ['Ford', '69,000 km', 0.0, 0.0, 0.0],
 ['Mahindra', '79900.0 km', 0.0, 0.0, 0.0],
 ['Mahindra', '65,000 km', 0.0, 0.0, 0.0],
 ['Mercedes-Benz', '90000.0 km', 0.0, 0.0, 1.0],
 ['Hyundai', '80,000 km', 1.0, 0.0, 1.0],
 ['Toyota', '37000.0 km', 0.0, 0.0, 0.0],
 ['Honda', '80,000 km', 1.0, 0.0, 1.0],
 ['Maruti Suzuki', '40,000 km', 1.0, 0.0, 0.0],
 ['Maruti Suzuki', '78,000 km', 0.0, 1.0, 1.0],
 ['Honda', '75,000 km', 0.0, 1.0, 1.0],
 ['Volkswagen', '65,000 km', 0.0, 1.0, 1.0],
 ['Tata', '100,413 km', 0.0, 0.0, 0.0],
 ['Mahindra', '76,000 km', 0.0, 0.0, 1.0],
 ['Land Rover', '53,500 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '38000.0 km', 1.0, 0.0, 0.0],
 ['Jaguar', '80,250 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '70,000 km', 1.0, 0.0, 0.0],
 ['BMW', '70,000 km', 0.0, 0.0, 1.0],
 ['Hyundai', '80,000 km', 0.0, 0.0, 1.0],
 ['Honda', '59,600 km', 0.0, 1.0, 1.0],
 ['Hyundai', '74000.0 km', 0.0, 0.0, 0.0],
 ['Hyundai', '68,000 km', 0.0, 1.0, 0.0],
 ['Hyundai', '90000.0 km', 0.0, 0.0, 1.0],
 ['Toyota', '180,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '15,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '35,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '72,300 km', 1.0, 0.0, 0.0],
 ['Maruti Suzuki', '54,000 km', 0.0, 1.0, 0.0],
 ['Toyota', '160,000 km', 0.0, 0.0, 1.0],
 ['Hyundai', '1,500 km', 0.0, 1.0, 0.0],
 ['Hyundai', '71,900 km', 1.0, 0.0, 1.0],
 ['Maruti Suzuki', '142,000 km', 1.0, 0.0, 1.0],
 ['Mercedes-Benz', '32,000 km', 0.0, 1.0, 1.0],
 ['Tata', '3,500 km', 1.0, 0.0, 0.0],
 ['Honda', '80,000 km', 0.0, 1.0, 1.0],
 ['Hyundai', '25,000 km', 0.0, 1.0, 1.0],
 ['Volkswagen', '77,948 km', 0.0, 0.0, 1.0],
 ['Mahindra', '111,000 km', 0.0, 0.0, 0.0],
 ['Mahindra', '52,000 km', 0.0, 0.0, 0.0],
 ['Mercedes-Benz', '23,000 km', 0.0, 1.0, 0.0],
 ['Mahindra', '78,000 km', 0.0, 0.0, 1.0],
 ['BMW', '61,000 km', 0.0, 0.0, 1.0],
 ['Hyundai', '65,000 km', 0.0, 1.0, 1.0],
 ['Audi', '76,000 km', 0.0, 1.0, 1.0],
 ['Toyota', '89,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '63,100 km', 0.0, 1.0, 1.0],
 ['Volkswagen', '80,000 km', 0.0, 0.0, 1.0],
 ['Toyota', '114,918 km', 0.0, 0.0, 0.0],
 ['Opel', '70,000 km', 0.0, 1.0, 1.0],
 ['Porsche', '15,000 km', 0.0, 1.0, 1.0],
 ['Honda', '74,000 km', 0.0, 1.0, 1.0],
 ['Skoda', '11,000 km', 0.0, 0.0, 0.0],
 ['Hyundai', '1234.0 km', 1.0, 0.0, 0.0],
 ['Datsun', '70,000 km', 0.0, 1.0, 1.0],
 ['Hyundai', '69000.0 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '91,000 km', 0.0, 0.0, 0.0],
 ['Skoda', '105,904 km', 0.0, 0.0, 1.0],
 ['Hyundai', '53,416 km', 0.0, 1.0, 1.0],
 ['Mahindra', '53,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '36,000 km', 0.0, 1.0, 1.0],
 ['MG', '15,744 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '19,500 km', 0.0, 1.0, 1.0],
 ['BMW', '69,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '0 km', 0.0, 1.0, 1.0],
 ['Ford', '75,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '62,000 km', 1.0, 0.0, 1.0],
 ['Kia', '0 km', 0.0, 0.0, 0.0],
 ['Mahindra', '180,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '23,000 km', 0.0, 1.0, 0.0],
 ['Mercedes-Benz', '21000.0 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '129,000 km', 0.0, 0.0, 0.0],
 ['Mahindra', '71,111 km', 0.0, 0.0, 0.0],
 ['Hyundai', '73,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '52,000 km', 1.0, 0.0, 1.0],
 ['Toyota', '90,000 km', 0.0, 1.0, 0.0],
 ['Toyota', '185,865 km', 0.0, 0.0, 0.0],
 ['Honda', '65,000 km', 0.0, 1.0, 1.0],
 ['Hyundai', '70000.0 km', 0.0, 1.0, 1.0],
 ['Audi', '95,000 km', 0.0, 0.0, 0.0],
 ['BMW', '25700.0 km', 0.0, 1.0, 1.0],
 ['Mahindra', '174,000 km', 0.0, 0.0, 0.0],
 ['Volkswagen', '70,000 km', 0.0, 1.0, 1.0],
 ['Tata', '66,800 km', 0.0, 1.0, 1.0],
 ['Hyundai', '57,000 km', 1.0, 0.0, 1.0],
 ['Renault', '40,000 km', 0.0, 1.0, 0.0],
 ['Mahindra', '31,000 km', 0.0, 1.0, 0.0],
 ['Audi', '45,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '40,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '70,000 km', 0.0, 1.0, 1.0],
 ['Honda', '76,000 km', 0.0, 1.0, 1.0],
 ['Hyundai', '100 km', 0.0, 1.0, 0.0],
 ['Hyundai', '80,000 km', 0.0, 0.0, 0.0],
 ['Honda', '68,000 km', 0.0, 1.0, 1.0],
 ['Volkswagen', '116,000 km', 0.0, 0.0, 0.0],
 ['Kia', '77,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '100,000 km', 1.0, 0.0, 1.0],
 ['Tata', '46,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '100,000 km', 0.0, 1.0, 1.0],
 ['Toyota', '140,000 km', 1.0, 0.0, 1.0],
 ['Mini', '31,900 km', 0.0, 1.0, 1.0],
 ['Toyota', '45000.0 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '45,700 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '59,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '34,000 km', 0.0, 1.0, 0.0],
 ['Hyundai', '77,665 km', 0.0, 1.0, 0.0],
 ['Hyundai', '79,810 km', 1.0, 0.0, 1.0],
 ['Jeep', '59,000 km', 0.0, 1.0, 1.0],
 ['Ford', '90000.0 km', 0.0, 0.0, 0.0],
 ['Hyundai', '30,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '41,000 km', 0.0, 1.0, 1.0],
 ['Hyundai', '74,000 km', 1.0, 0.0, 1.0],
 ['Maruti Suzuki', '61,000 km', 1.0, 0.0, 1.0],
 ['Hyundai', '42,900 km', 1.0, 0.0, 0.0],
 ['Maruti Suzuki', '87,000 km', 1.0, 0.0, 1.0],
 ['Mahindra', '55000.0 km', 0.0, 0.0, 0.0],
 ['Hyundai', '68,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '28 km', 1.0, 0.0, 0.0],
 ['Audi', '75,000 km', 0.0, 0.0, 0.0],
 ['Tata', '61,000 km', 1.0, 0.0, 0.0],
 ['Renault', '45,011 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '35,000 km', 0.0, 1.0, 0.0],
 ['BMW', '25,000 km', 0.0, 1.0, 0.0],
 ['Honda', '70,000 km', 0.0, 1.0, 1.0],
 ['Toyota', '57,000 km', 0.0, 0.0, 0.0],
 ['Toyota', '35,000 km', 0.0, 0.0, 0.0],
 ['Hyundai', '65,891 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '65000.0 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '33,251 km', 0.0, 1.0, 1.0],
 ['Volkswagen', '42,000 km', 0.0, 1.0, 0.0],
 ['Hyundai', '69,000 km', 0.0, 1.0, 1.0],
 ['Toyota', '150,000 km', 0.0, 0.0, 1.0],
 ['Chevrolet', '175,300 km', 0.0, 0.0, 1.0],
 ['Honda', '93,000 km', 1.0, 0.0, 1.0],
 ['Hyundai', '69000.0 km', 0.0, 0.0, 0.0],
 ['Hyundai', '53,000 km', 1.0, 0.0, 0.0],
 ['Hyundai', '75,000 km', 1.0, 0.0, 1.0],
 ['Maruti Suzuki', '33,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '59000.0 km', 1.0, 0.0, 0.0],
 ['Maruti Suzuki', '27,800 km', 0.0, 0.0, 0.0],
 ['Audi', '42,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '38000.0 km', 0.0, 1.0, 0.0],
 ['Hyundai', '26,000 km', 0.0, 1.0, 1.0],
 ['Mahindra', '28,000 km', 0.0, 0.0, 0.0],
 ['Volkswagen', '35000.0 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '59,000 km', 0.0, 1.0, 1.0],
 ['Toyota', '22310.0 km', 0.0, 0.0, 0.0],
 ['BMW', '31,000 km', 0.0, 0.0, 0.0],
 ['Kia', '18,000 km', 0.0, 1.0, 0.0],
 ['Audi', '85,000 km', 0.0, 0.0, 0.0],
 ['Ford', '53,000 km', 0.0, 0.0, 0.0],
 ['BMW', '75000.0 km', 0.0, 0.0, 1.0],
 ['Honda', '59,000 km', 0.0, 1.0, 1.0],
 ['Mercedes-Benz', '130,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '82,000 km', 0.0, 1.0, 0.0],
 ['Tata', '29,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '15,505 km', 0.0, 1.0, 1.0],
 ['Toyota', '190,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '62,000 km', 0.0, 1.0, 1.0],
 ['Ford', '122,000 km', 0.0, 0.0, 0.0],
 ['Hyundai', '82,000 km', 0.0, 0.0, 0.0],
 ['Volkswagen', '11,021 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '3,240 km', 0.0, 1.0, 1.0],
 ['Honda', nan, 0.0, 1.0, 0.0],
 ['Toyota', '150,000 km', 0.0, 0.0, 1.0],
 ['Jeep', '78,000 km', 0.0, 1.0, 0.0],
 ['Honda', '76,000 km', 0.0, 1.0, 1.0],
 ['Honda', '69,000 km', 0.0, 1.0, 1.0],
 ['Toyota', '24,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '75,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '12500.0 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '67,000 km', 0.0, 1.0, 1.0],
 ['Hyundai', '63,000 km', 0.0, 1.0, 0.0],
 ['Mercedes-Benz', '20,000 km', 0.0, 0.0, 0.0],
 ['Kia', '59,000 km', 0.0, 1.0, 0.0],
 ['Mitsubishi', '225,000 km', 0.0, 0.0, 1.0],
 ['Mercedes-Benz', '41,000 km', 0.0, 1.0, 1.0],
 ['MG', '18,000 km', 0.0, 0.0, 0.0],
 ['Honda', '98,000 km', 1.0, 0.0, 1.0],
 ['Honda', '119,000 km', 1.0, 0.0, 1.0],
 ['Mahindra', '70,013 km', 0.0, 0.0, 0.0],
 ['Mahindra', '71,000 km', 0.0, 0.0, 1.0],
 ['Skoda', '65,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '40,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '42,470 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '59,530 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '25,500 km', 0.0, 0.0, 0.0],
 ['Nissan', '72900.0 km', 1.0, 0.0, 0.0],
 ['Maruti Suzuki', '61,382 km', 0.0, 1.0, 0.0],
 ['Chevrolet', '85,000 km', 0.0, 0.0, 1.0],
 ['Ford', '97,000 km', 0.0, 1.0, 1.0],
 ['Mercedes-Benz', '51,000 km', 0.0, 0.0, 1.0],
 ['Tata', '52,000 km', 1.0, 0.0, 0.0],
 ['Maruti Suzuki', '47,110 km', 0.0, 1.0, 1.0],
 ['Tata', '80,000 km', 0.0, 0.0, 1.0],
 ['Mahindra', '66,000 km', 0.0, 1.0, 0.0],
 ['Hyundai', '56,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '106,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '85,000 km', 0.0, 1.0, 0.0],
 ['Tata', '43,000 km', 1.0, 0.0, 0.0],
 ['Maruti Suzuki', '31,000 km', 1.0, 0.0, 0.0],
 ['Toyota', '100,906 km', 0.0, 1.0, 0.0],
 ['Mercedes-Benz', '75000.0 km', 0.0, 0.0, 0.0],
 ['Hyundai', '62,000 km', 1.0, 0.0, 1.0],
 ['Land Rover', '89000.0 km', 0.0, 0.0, 1.0],
 ['Toyota', '38,100 km', 1.0, 0.0, 0.0],
 ['Mercedes-Benz', '77,600 km', 0.0, 0.0, 1.0],
 ['Honda', '80,000 km', 0.0, 0.0, 0.0],
 ['Maruti Suzuki', '100,000 km', 1.0, 0.0, 1.0],
 ['Hyundai', '70,000 km', 0.0, 1.0, 1.0],
 ['Maruti Suzuki', '5656.0 km', 0.0, 0.0, 0.0],
 ['Honda', '69,500 km', 1.0, 0.0, 1.0],
 ['Land Rover', '28,000 km', 0.0, 1.0, 0.0],
 ['Maruti Suzuki', '65,000 km', 1.0, 0.0, 1.0],
 ['Kia', '15,000 km', 0.0, 1.0, 0.0],
 ['Audi', '45,000 km', 0.0, 0.0, 1.0],
 ['Honda', '78,000 km', 0.0, 0.0, 1.0],
 ['Mahindra', '61,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '115,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '85,000 km', 1.0, 0.0, 1.0],
 ['Maruti Suzuki', '51,700 km', 0.0, 1.0, 1.0],
 ['Mahindra', '90,000 km', 0.0, 0.0, 1.0],
 ['Maruti Suzuki', '31853.0 km', 1.0, 0.0, 0.0],
 ['Kia', '47,000 km', 0.0, 1.0, 0.0],
 ['Hyundai', '89,000 km', 0.0, 1.0, 1.0],

In [54]:
counts = df['Brand'].value_counts()

In [46]:
threshold = 100
df['Brand'].nunique()

39

In [56]:
repl =counts[counts <= threshold].index

In [58]:
pd.get_dummies(df['Brand'].replace(repl , 'uncommon') , dtype = int)

,Audi,BMW,Ford,Honda,Hyundai,Kia,Mahindra,Maruti Suzuki,Mercedes-Benz,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9577,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
9578,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
9579,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
9580,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
9581,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0